import { generateAgentsMd } from './generators/agents-md.js';
import type { AgentsMdOptions } from './generators/agents-md.js';
import { generateCodexMcpConfig } from './generators/mcp-config.js';
import type { CodexMcpConfigOptions } from './generators/mcp-config.js';
import { generateReviewSkill } from './generators/review-skill.js';
import type { ReviewSkillOptions } from './generators/review-skill.js';
import { generateReviewReportTemplate } from './generators/review-report-template.js';

/**
 * Options for the Codex plugin installation.
 */
export interface InstallCodexPluginOptions {
  /** Project name for AGENTS.md header. */
  projectName?: string;
  /** Custom reviewer agent name. */
  reviewerAgent?: string;
  /** Custom builder agent name. */
  builderAgent?: string;
  /** Path to the MCP server entry point. */
  mcpServerPath?: string;
  /** Path to the AgentMesa workspace directory. */
  mesaDir?: string;
}

/**
 * Summary of files generated by the Codex plugin installer.
 */
export interface InstallCodexPluginSummary {
  /** Content for AGENTS.md to write to the project root. */
  agentsMd: string;
  /** TOML config snippet for .codex/config.toml. */
  mcpConfig: string;
  /** Review skill definition object. */
  reviewSkill: { name: string; description: string; instructions: string };
  /** Review report markdown template. */
  reviewReportTemplate: string;
  /** List of files that should be written. */
  files: Array<{ path: string; description: string }>;
}

/**
 * Orchestrates all Codex plugin generators and returns the content
 * that should be written to the project.
 *
 * This is a pure function — it returns strings rather than writing
 * to disk, making it easy to test and integrate.
 *
 * @param _rootDir - The project root directory (reserved for future use).
 * @param options - Configuration options for the generators.
 * @returns A summary object with all generated content.
 */
export function installCodexPlugin(
  _rootDir: string,
  options: InstallCodexPluginOptions = {},
): InstallCodexPluginSummary {
  const agentsMdOptions: AgentsMdOptions = {
    projectName: options.projectName,
    reviewerAgent: options.reviewerAgent,
    builderAgent: options.builderAgent,
  };

  const mcpConfigOptions: CodexMcpConfigOptions = {
    mcpServerPath: options.mcpServerPath,
  };

  const reviewSkillOptions: ReviewSkillOptions = {
    mesaDir: options.mesaDir,
  };

  const agentsMd = generateAgentsMd(agentsMdOptions);
  const mcpConfig = generateCodexMcpConfig(mcpConfigOptions);
  const reviewSkill = generateReviewSkill(reviewSkillOptions);
  const reviewReportTemplate = generateReviewReportTemplate();

  return {
    agentsMd,
    mcpConfig,
    reviewSkill,
    reviewReportTemplate,
    files: [
      { path: 'AGENTS.md', description: 'Agent role definitions for Codex CLI' },
      { path: '.codex/config.toml', description: 'MCP server configuration (append snippet)' },
      { path: `.codex/skills/${reviewSkill.name}.md`, description: 'Review skill definition' },
    ],
  };
}
