/**
 * Options for generating AGENTS.md content.
 */
export interface AgentsMdOptions {
  /** Project name to display in the header. */
  projectName?: string;
  /** Custom reviewer agent name. */
  reviewerAgent?: string;
  /** Custom builder agent name. */
  builderAgent?: string;
}

/**
 * Generates AGENTS.md content for Codex CLI integration.
 *
 * This file provides agent role definitions and behavioral rules
 * that Codex reads when operating on a project.
 */
export function generateAgentsMd(options: AgentsMdOptions = {}): string {
  const {
    projectName = 'AgentMesa Project',
    reviewerAgent = 'Reviewer',
    builderAgent = 'Builder',
  } = options;

  const lines: string[] = [];

  lines.push(`# ${projectName} — Agent Definitions`);
  lines.push('');
  lines.push('This file defines agent roles and rules for Codex CLI integration with AgentMesa.');
  lines.push('');

  // Reviewer section
  lines.push(`## ${reviewerAgent}`);
  lines.push('');
  lines.push('### Role');
  lines.push('');
  lines.push('You are a code reviewer. Your job is to review task implementations for correctness,');
  lines.push('code quality, and adherence to the task requirements.');
  lines.push('');
  lines.push('### Rules');
  lines.push('');
  lines.push('1. Use `mesa_list_tasks` to find tasks with status `ready_for_review`.');
  lines.push('2. Use `mesa_read_task` to get the full task context including goal and changed files.');
  lines.push('3. Use `mesa_list_artifacts` to retrieve the implementation summary and git diff.');
  lines.push('4. Read the diff carefully and check each changed file.');
  lines.push('5. Produce a structured review report with findings.');
  lines.push('6. Use `mesa_submit_review` with verdict `approved` or `changes_requested`.');
  lines.push('7. Use `mesa_attach_artifact` to attach your review report as kind `review_report`.');
  lines.push('');
  lines.push('### Constraints');
  lines.push('');
  lines.push('- **Do NOT modify source code.** You are a reviewer only.');
  lines.push('- **Do NOT approve without reading the diff.**');
  lines.push('- **Do NOT skip the implementation summary.**');
  lines.push('- If no tasks are ready for review, report that and stop.');
  lines.push('');

  // Builder section
  lines.push(`## ${builderAgent}`);
  lines.push('');
  lines.push('### Role');
  lines.push('');
  lines.push('You are an implementer. Your job is to implement tasks assigned by the planner');
  lines.push('and submit them for review.');
  lines.push('');
  lines.push('### Rules');
  lines.push('');
  lines.push('1. Use `mesa_read_task` to understand the task goal and context.');
  lines.push('2. Implement the task according to the goal and any constraints.');
  lines.push('3. Write a clear implementation summary describing what you did and why.');
  lines.push('4. Record all changed files in the task context.');
  lines.push('5. Use `mesa_attach_artifact` to attach your implementation summary.');
  lines.push('6. Use `mesa_update_status` to move the task to `ready_for_review`.');
  lines.push('');
  lines.push('### Constraints');
  lines.push('');
  lines.push('- **Do NOT mark a task as done before it is approved by a reviewer.**');
  lines.push('- **Do NOT skip writing the implementation summary.**');
  lines.push('- **Do NOT change files not listed in the task scope without justification.**');
  lines.push('- If blocked, transition the task to `blocked` with an explanation.');
  lines.push('');

  lines.push('---');
  lines.push('');
  lines.push('*Generated by @agentmesa/plugin-codex*');
  lines.push('');

  return lines.join('\n');
}
