/**
 * Options for generating the Codex exec shell script.
 */
export interface CodexExecScriptOptions {
  /** The task ID to review. */
  taskId: string;
  /** Path to the AgentMesa workspace root (the directory containing `.agentmesa/`). */
  mesaDir?: string;
}

/**
 * Generates a shell script for non-interactive Codex review execution.
 *
 * This script only verifies the task precondition and launches Codex with
 * the review skill. Submitting the verdict and attaching the review report
 * happen inside that Codex run via the `mesa_submit_review` and
 * `mesa_attach_artifact` MCP tools (see `agentmesa-review` skill instructions)
 * — there is no CLI equivalent for writing those, so the script does not
 * attempt to re-do that work from shell.
 */
export function generateCodexExecScript(options: CodexExecScriptOptions): string {
  const { taskId, mesaDir = '.' } = options;

  const lines: string[] = [];

  lines.push('#!/usr/bin/env bash');
  lines.push('# Generated by @agentmesa/plugin-codex');
  lines.push('# Non-interactive Codex review script for AgentMesa task');
  lines.push('set -euo pipefail');
  lines.push('');
  lines.push(`TASK_ID="${taskId}"`);
  lines.push(`MESA_DIR="${mesaDir}"`);
  lines.push('');
  lines.push('cd "${MESA_DIR}"');
  lines.push('');

  lines.push('# Step 1: Verify the task exists and is ready for review');
  lines.push('echo "Checking task ${TASK_ID} status..."');
  lines.push('TASK_STATUS=$(mesa task show "${TASK_ID}" --json | jq -r .status)');
  lines.push('');
  lines.push('if [ "${TASK_STATUS}" != "ready_for_review" ]; then');
  lines.push('  echo "Error: Task ${TASK_ID} is in status ${TASK_STATUS}, expected ready_for_review"');
  lines.push('  exit 1');
  lines.push('fi');
  lines.push('');

  lines.push('# Step 2: Run Codex with the review skill. The skill instructions call');
  lines.push('# mesa_submit_review and mesa_attach_artifact over MCP directly, so the');
  lines.push('# verdict and review report are written before this command returns.');
  lines.push('echo "Running Codex review for task ${TASK_ID}..."');
  lines.push('REVIEW_OUTPUT=$(codex --skill agentmesa-review \\');
  lines.push('  --quiet \\');
  lines.push('  --non-interactive \\');
  lines.push(`  "Review task ${taskId} in workspace ${mesaDir}")`);
  lines.push('');

  lines.push('# Step 3: Echo the transcript for local debugging.');
  lines.push('echo "${REVIEW_OUTPUT}"');
  lines.push('');
  lines.push('echo "Review complete for task ${TASK_ID}"');
  lines.push('');

  return lines.join('\n');
}
