/**
 * Options for generating the Codex exec shell script.
 */
export interface CodexExecScriptOptions {
  /** The task ID to review. */
  taskId: string;
  /** Path to the AgentMesa workspace directory. */
  mesaDir?: string;
}

/**
 * Generates a shell script for non-interactive Codex review execution.
 *
 * This script reads the task from AgentMesa, runs Codex with the
 * review skill, and captures the output as a review artifact.
 */
export function generateCodexExecScript(options: CodexExecScriptOptions): string {
  const { taskId, mesaDir = '.mesa' } = options;

  const lines: string[] = [];

  lines.push('#!/usr/bin/env bash');
  lines.push('# Generated by @agentmesa/plugin-codex');
  lines.push('# Non-interactive Codex review script for AgentMesa task');
  lines.push('set -euo pipefail');
  lines.push('');
  lines.push(`TASK_ID="${taskId}"`);
  lines.push(`MESA_DIR="${mesaDir}"`);
  lines.push('');

  lines.push('# Step 1: Verify the task exists and is ready for review');
  lines.push('echo "Checking task ${TASK_ID} status..."');
  lines.push('TASK_STATUS=$(mesa task read "${TASK_ID}" --mesa-dir "${MESA_DIR}" --format json | jq -r .status)');
  lines.push('');
  lines.push('if [ "${TASK_STATUS}" != "ready_for_review" ]; then');
  lines.push('  echo "Error: Task ${TASK_ID} is in status ${TASK_STATUS}, expected ready_for_review"');
  lines.push('  exit 1');
  lines.push('fi');
  lines.push('');

  lines.push('# Step 2: Run Codex with the review skill');
  lines.push('echo "Running Codex review for task ${TASK_ID}..."');
  lines.push('REVIEW_OUTPUT=$(codex --skill agentmesa-review \\');
  lines.push('  --quiet \\');
  lines.push('  --non-interactive \\');
  lines.push(`  "Review task ${taskId} in workspace ${mesaDir}")`);
  lines.push('');

  lines.push('# Step 3: Capture the review output');
  lines.push('echo "Capturing review output..."');
  lines.push('REVIEW_FILE=$(mktemp /tmp/mesa-review-XXXXXX.md)');
  lines.push('echo "${REVIEW_OUTPUT}" > "${REVIEW_FILE}"');
  lines.push('');

  lines.push('# Step 4: Attach the review report as an artifact');
  lines.push('echo "Attaching review artifact..."');
  lines.push('mesa artifact attach "${TASK_ID}" \\');
  lines.push('  --kind review_report \\');
  lines.push('  --content-file "${REVIEW_FILE}" \\');
  lines.push('  --mesa-dir "${MESA_DIR}"');
  lines.push('');

  lines.push('# Step 5: Clean up');
  lines.push('rm -f "${REVIEW_FILE}"');
  lines.push('');
  lines.push('echo "Review complete for task ${TASK_ID}"');
  lines.push('');

  return lines.join('\n');
}
