import type { RoleCapability } from './types.js';

export function defineRoleCapabilities(): RoleCapability {
  return {
    owner: [
      'read_task',
      'write_task',
      'change_status',
      'post_message',
      'create_artifact',
      'archive_task',
      'delete_task',
      'manage_agents',
      'manage_meetings',
      'read_events',
      'read_projections',
      'rebuild_projections',
      'inspect_transports',
    ],
    chair: [
      'read_task',
      'write_task',
      'change_status',
      'post_message',
      'create_artifact',
      'modify_source',
      'run_command',
      'push_code',
      'merge_pr',
      'archive_task',
      'delete_task',
      'manage_agents',
      'manage_meetings',
      'read_events',
      'read_projections',
      'rebuild_projections',
      'inspect_transports',
    ],
    planner: [
      'read_task',
      'write_task',
      'post_message',
      'manage_meetings',
      'read_events',
      'read_projections',
    ],
    builder: [
      'read_task',
      'write_task',
      'change_status',
      'post_message',
      'create_artifact',
      'modify_source',
      'run_command',
      'read_events',
      'read_projections',
    ],
    reviewer: [
      'read_task',
      'post_message',
      'create_artifact',
      'change_status',
      'read_events',
      'read_projections',
    ],
    tester: [
      'read_task',
      'post_message',
      'create_artifact',
      'run_command',
      'read_events',
      'read_projections',
    ],
    documenter: [
      'read_task',
      'post_message',
      'create_artifact',
      'read_events',
      'read_projections',
    ],
    maintainer: [
      'read_task',
      'write_task',
      'change_status',
      'post_message',
      'create_artifact',
      'run_command',
      'manage_agents',
      'manage_meetings',
      'archive_task',
      'delete_task',
      'read_events',
      'read_projections',
      'rebuild_projections',
      'inspect_transports',
    ],
    researcher: [
      'read_task',
      'post_message',
      'create_artifact',
      'read_events',
      'read_projections',
    ],
    custom: [
      'read_task',
    ],
    admin: [
      'read_task',
      'write_task',
      'change_status',
      'post_message',
      'create_artifact',
      'archive_task',
      'delete_task',
      'manage_agents',
      'manage_meetings',
      'read_events',
      'read_projections',
      'rebuild_projections',
      'inspect_transports',
    ],
    connector: [
      'read_task',
      'post_message',
      'create_artifact',
      'read_events',
      'read_projections',
    ],
    ci: [
      'read_task',
      'post_message',
      'create_artifact',
      'read_events',
      'read_projections',
    ],
    system: [
      'read_task',
      'read_events',
      'read_projections',
      'rebuild_projections',
    ],
  };
}
