import type { RoleCapability } from './types.js';

export function defineRoleCapabilities(): RoleCapability {
  return {
    // Owner mirrors the core engine's bypass semantics (RoleBasedPolicyEngine
    // short-circuits to allow for owners): every PolicyAction is granted,
    // including the code-execution vocabulary (modify_source / run_command /
    // push_code / merge_pr). Without this, the runner permission bridge would
    // deny Bash/Write tool calls for owners while core allows them.
    owner: [
      'read_task',
      'write_task',
      'change_status',
      'post_message',
      'create_artifact',
      'modify_source',
      'run_command',
      'push_code',
      'merge_pr',
      'archive_task',
      'delete_task',
      'manage_agents',
      'manage_meetings',
      'read_events',
      'read_projections',
      'rebuild_projections',
      'inspect_transports',
      'manage_runs',
      'manage_workflows',
      'manage_rooms',
    ],
    chair: [
      'read_task',
      'write_task',
      'change_status',
      'post_message',
      'create_artifact',
      'modify_source',
      'run_command',
      'push_code',
      'merge_pr',
      'archive_task',
      'delete_task',
      'manage_agents',
      'manage_meetings',
      'read_events',
      'read_projections',
      'rebuild_projections',
      'inspect_transports',
      'manage_runs',
      'manage_workflows',
      'manage_rooms',
    ],
    planner: [
      'read_task',
      'write_task',
      'post_message',
      'manage_meetings',
      'read_events',
      'read_projections',
      'manage_runs',
    ],
    builder: [
      'read_task',
      'write_task',
      'change_status',
      'post_message',
      'create_artifact',
      'modify_source',
      'run_command',
      'read_events',
      'read_projections',
      'manage_runs',
      'manage_meetings',
      'manage_agents',
      'manage_rooms',
    ],
    reviewer: [
      'read_task',
      'post_message',
      'create_artifact',
      'change_status',
      'read_events',
      'read_projections',
      'manage_runs',
    ],
    tester: [
      'read_task',
      'post_message',
      'create_artifact',
      'run_command',
      'read_events',
      'read_projections',
      'manage_runs',
    ],
    documenter: [
      'read_task',
      'post_message',
      'create_artifact',
      'read_events',
      'read_projections',
    ],
    maintainer: [
      'read_task',
      'write_task',
      'change_status',
      'post_message',
      'create_artifact',
      'run_command',
      'manage_agents',
      'manage_meetings',
      'archive_task',
      'delete_task',
      'read_events',
      'read_projections',
      'rebuild_projections',
      'inspect_transports',
      'manage_runs',
      'manage_workflows',
      'manage_rooms',
    ],
    researcher: [
      'read_task',
      'post_message',
      'create_artifact',
      'read_events',
      'read_projections',
    ],
    custom: [
      'read_task',
    ],
    // Admin mirrors the core vocabulary (all core capabilities, like core's
    // admin) but stays deliberately off the code-execution vocabulary —
    // administer ≠ execute. Only owner carries the full bypass semantics.
    admin: [
      'read_task',
      'write_task',
      'change_status',
      'post_message',
      'create_artifact',
      'archive_task',
      'delete_task',
      'manage_agents',
      'manage_meetings',
      'read_events',
      'read_projections',
      'rebuild_projections',
      'inspect_transports',
      'manage_runs',
      'manage_workflows',
      'manage_rooms',
    ],
    connector: [
      'read_task',
      'post_message',
      'create_artifact',
      'read_events',
      'read_projections',
    ],
    ci: [
      'read_task',
      'post_message',
      'create_artifact',
      'read_events',
      'read_projections',
      'manage_runs',
    ],
    system: [
      'read_task',
      'read_events',
      'read_projections',
      'rebuild_projections',
    ],
  };
}
